name: chat_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  firebase_auth: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf
  assets:
    - assets/images/ingredients.png
    - assets/images/recipe.png
    - assets/images/spices.png
    - assets/images/cereals.png
    - assets/images/eggs.png
    - assets/images/fruit.png
    - assets/images/meat.png
    - assets/images/milk.png
    - assets/images/seafood.png
    - assets/images/sugar.png
    - assets/images/vegetable.png
